### ISSUE TITLE
error: request for member ‘vote_results_valid’ in something not a structure or union

### ISSUE THREAD

**Issue by mill99** [X-CASH-official/xcash-dpops#25]
Hi team, I've got a xcash-dpops compilation (make clean ; make debug -j nproc) error after updating with autoinstaller.sh

 Currently Building File 66 Out Of 66: build/./src/functions/block_verifiers_functions/block_verifiers_functions.c.o
src/functions/block_verifiers_functions/block_verifiers_thread_server_functions/block_verifiers_thread_server_functions.c: In function ‘check_reserve_proofs_timer_thread’:
src/functions/block_verifiers_functions/block_verifiers_thread_server_functions/block_verifiers_thread_server_functions.c:800:173: error: request for member ‘vote_results_valid’ in something not a structure or union
         fprintf(stderr,"\033[1;32m%d / %d network data nodes have the same created data and block with %d / %d network data nodes\033[0m\n\n",network_data_node_valid_amount.vote_results_valid,NETWORK_DATA_NODES_AMOUNT-1);
                                                                                                                                                                             ^
Makefile:70: recipe for target 'build/./src/functions/block_verifiers_functions/block_verifiers_thread_server_functions/block_verifiers_thread_server_functions.c.o' failed
make: *** [build/./src/functions/block_verifiers_functions/block_verifiers_thread_server_functions/block_verifiers_thread_server_functions.c.o] Error 1
make: *** Waiting for unfinished jobs....

Same problem with a fresh git clone of the X-CASH-official/xcash-dpops github repo :(

is somebody could help me to solve this compilation problem plz ?

just when I will register my delegate (shared) node -_-''

**Comment by zachhildreth** [comment]
Hi @mill99 
I just noticed this today when updating some code for an alpha test.

It was a code error from a previous code addition I did a few days ago.

You should be able to pull the new changes and build successfully now.

Thanks!

**Comment by mill99** [comment]
Thank you Zach for your quick answer

Node update in progress !

Happy to help you with this feedback :)
