### ISSUE TITLE
[bug] Can't create swapfile for system with low RAM on non-root user

### ISSUE THREAD

**Issue by plbgnt** [X-CASH-official/xcash-dpops#28]
# 🐛 BUG REPORT 

**Expected Behavior**
When a user install the xcash-dpops program on a low RAM server (less than 10GB), then the installer automatically creates a swap file to simulate more RAM. 

https://github.com/X-CASH-official/xcash-dpops/blob/e52d8d590ae251b303a46bfda94002d83e1de837/scripts/autoinstaller/autoinstaller.sh#L2012-L2024

**Current Behavior**
When installing on a non-root user session, the scripts freeze with the following error: 
![issue](https://cdn.discordapp.com/attachments/586183390768922634/725326354672779284/Issue_1.PNG)

**Possible Solution**

**Steps to Reproduce (for bugs)**

1. Initialized server and created new user `xcash` and give it sudo access with `usermod`.
2. Installed xcash-dpops with the auto-installer script.

**Comment by zachhildreth** [comment]
Closing this, as it seems to be fixed from 48e5f6b464c0f16f7f753c1bb4d723ec2c126917
