### ISSUE TITLE
[feat] Add management script

### ISSUE THREAD

**Issue by rradu92** [X-CASH-official/xcash-dpops#29]
# Description
- Add a simple management script to check, start and restart services, see the block height and get node's balance without stopping it

## Type of change
- [x] New feature (non-breaking change which adds functionality)

**Comment by zachhildreth** [comment]
Thanks for creating this @rradu92 
I will take a look at it and then pull it in once we have started beta as I want as little commits as possible from the last successfully alpha to the beta.
