### ISSUE TITLE
[bug] brand new vps install of Ubuntu 20.04 lacks iptables and crashes script

### ISSUE THREAD

**Issue by CygnusMiner** [X-CASH-official/xcash-dpops#35]
# 🐛 BUG REPORT 
the install script assumes iptables is installed and fails if not. A base install of Ubuntu 20.04 on a Hetzner auction will show this if you immediately run the installer:
----------------------
Installing The Firewall/root/firewall_script.sh: 6: iptables: not found
/root/firewall_script.sh: 7: iptables: not found
/root/firewall_script.sh: 8: iptables: not found
/root/firewall_script.sh: 10: iptables: not found
/root/firewall_script.sh: 11: iptables: not found
/root/firewall_script.sh: 12: iptables: not found
/root/firewall_script.sh: 13: iptables: not found
/root/firewall_script.sh: 14: iptables: not found
etc...
/root/firewall_script.sh: 100: iptables: not found
-bash-5.0#
----------------------

**Expected Behavior**

The installer itself should check if iptables is installed and if not manually install it. Or at least try to install iptables by default.

**Current Behavior**

The script proceeds as if iptables was already installed and fails if it's not there.

**Possible Solution**

add iptables to the XCASH_DPOPS_PACKAGES environment variable.

**Steps to Reproduce (for bugs)**

Do a base install of 20.04 on a Hetzner vps. Attempt to install a delegate.

**Context**

Failure during an initial delegate install attempt.

**Your Environment**

Brand new Ubuntu 20.04 installed server immediately followed by an install (#1) choice from the autoinstaller.sh

- Version used:
- Environment name and version (e.g. node.js v10.15.3): autoinstaller.sh script
- Server type and version: Hetzner auction
- Operating System and version: Ubuntu 20.04

**Comment by n3me5is-git** [comment]
It could be an issue of 20.04. Check this: https://serverfault.com/questions/1028682/iptables-kernel-module-missing-after-upgrade-from-ubuntu-18-04-20-04
Check if iptables is installed (it should be!) with
```sh
which iptables
```
Mine is in `/sbin/iptables`
Try installing/reinstalling it with
```sh
sudo apt-get install --reinstall iptables
```
If this not works (`iptables -L` gives an error) try with
```sh
sudo apt-get install --reinstall linux-modules-$(uname -r)
```

**Comment by n3me5is-git** [comment]
Can you report the output of the commands? Maybe we could add a check in the script, so if iptables is not installed or the command fails it tries to reinstall it. But it's strange, it seems a bug related to ubuntu or maybe a ENV issue...

**Comment by CygnusMiner** [comment]
I had already installed it manually, but the reinstall command seemed to work just fine:

root@swan-x ~ # sudo apt-get install --reinstall iptables
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/390 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 63228 files and directories currently installed.)
Preparing to unpack .../iptables_1.8.4-3ubuntu2_amd64.deb ...
Unpacking iptables (1.8.4-3ubuntu2) over (1.8.4-3ubuntu2) ...
Setting up iptables (1.8.4-3ubuntu2) ...

**Comment by CygnusMiner** [comment]
What is interesting is that happened on a base reinstall of my Hetzner auction machine. However, a base install of 20.04 on a vps shows iptables immediately available after install. :thinking: I wonder if this is actually just a flaw in Hetzner's auction install image...

**Comment by n3me5is-git** [comment]
is it working now?

**Comment by CygnusMiner** [comment]
Once I wiped out the delegate half-install and manually installed iptables, the install script completed without an issue.

**Comment by n3me5is-git** [comment]
I added to my autoinstaller a command to reinstall iptables before installing the firewall, just in case...
This should be sufficient to solve issues like this (that are not x-cash related or OS related, since iptables should be there in a stock ubuntu 18.04/20.04 server distro, but a reinstall command doesn't hurt)

**Comment by zachhildreth** [comment]
Seems to be fixed now with 
@zachhildreth commit 532508a1a4dfa4c04121bac9870d82fb312abd6a
@n3me5is-git commit  e573b8944f7cdbb7a6012caf9dfb87853a49dacd
