### ISSUE TITLE
[bug]  autoinstaller.sh: choosing  #11  = "Restart Programs"  runs "Configure Installation"

### ISSUE THREAD

**Issue by xcash-rocks** [X-CASH-official/xcash-dpops#46]
# 🐛 BUG REPORT 
**Expected Behavior**

~: bash -c "$(curl -sSL https://raw.githubusercontent.com/X-CASH-official/xcash-dpops/master/scripts/autoinstaller/autoinstaller.sh)"

Choose: #11  = "Restart Programs" 

Should call:
  stop_systemd_service_files
  start_systemd_service_files

**Current Behavior**

~: bash -c "$(curl -sSL https://raw.githubusercontent.com/X-CASH-official/xcash-dpops/master/scripts/autoinstaller/autoinstaller.sh)"

Choose: #11  = "Restart Programs"  

Runs "Configure Installation":
"WARNING: Old wallet, old block verifier key and old settings (service files)
will be overwritten if already existent! Please make a backup if required!
Press ENTER to continue or press Ctrl + C to cancel! "

See: [https://i.imgur.com/gbqQTX6.png](https://i.imgur.com/gbqQTX6.png)

**Your Environment**

Ubuntu 18.04 as sudoer

**Comment by zachhildreth** [comment]
Hi @xcash-rocks I can not replicate the error? I have only 2 commits since your post, but did not change any menu layouts in them.

can you try again 
`source <(curl -sSL https://raw.githubusercontent.com/X-CASH-official/xcash-dpops/master/scripts/autoinstaller/autoinstaller.sh)` 

and let me know if choosing 11 should say `This is an invalid option since xcash-dpops is not installed`

Thanks

**Comment by xcash-rocks** [comment]
Hi @zachhildreth,

nope, choosing 11 says:   
WARNING: Old wallet, old block verifier key and old settings (service files)
will be overwritten if already existent! Please make a backup if required!
Press ENTER to continue or press Ctrl + C to cancel!


See Screenshot: [https://i.imgur.com/lddEjgO.png](https://i.imgur.com/lddEjgO.png)

**Comment by zachhildreth** [comment]
Hi @xcash-rocks If you cant test again, it should work now, there was a bug in the autoinstaller

**Comment by xcash-rocks** [comment]
Hi @zachhildreth,

it works now!

[https://i.imgur.com/xMy4oQZ.png](https://i.imgur.com/xMy4oQZ.png)
