### ISSUE TITLE
[bug] New installer not working with LXC_autoinstaller anymore

### ISSUE THREAD

**Issue by n3me5is-git** [X-CASH-official/xcash-dpops#47]
# 🐛 BUG REPORT 

With the new modifications, the LXC_autoinstaller is not working anymore:
- sed -i is icompatible with LXC container architecture, must use sed_services function (like in the other services-related functions)
- number associated to autoinstaller options changed, in particular the firewall (used for host FW install) and the configure delegate

This needs fixes both in the autoinstaller.sh and LXC_autoinstaller.sh

I will check the added modifications today/tomorrow and add the PR with the fixes. 
If someone is using the LXC_autoinstaller, do not use the new autoinstaller version, it won't work.

**Comment by n3me5is-git** [comment]
PR almost done....

@zachhildreth I noticed that in the install_node() you are using a firewall script without the customizable SSH port (default 22). Is it the wanted behavior for this install option or better to add the possibility to specify the port used also there?

**Comment by n3me5is-git** [comment]
#48 should fix the compatibility with LXC_installer. Minor bugfix included and added the possibility to specify the SSH port used also for the node (daemon only) install option.

**Comment by zachhildreth** [comment]
closed due to @n3me5is-git providing the fix
