### ISSUE TITLE
block reward value in api

### ISSUE THREAD

**Issue by neppers2** [X-CASH-official/xcash-dpops#56]
Could we have the block reward value in the api somewhere?

**Comment by AnimusXCASH** [comment]
Reward value as in Xcash in block or conversion to fiat?

**Comment by AnimusXCASH** [comment]
You can get block reward in xcash through [X-Cash explorer site](https://explorer.x-cash.org/API) by using the api endpoint either:
Last block found = https://explorer.x-cash.org/getlastblockdata
Custom param where parameter can be either block height or block hash =  https://explorer.x-cash.org/getblockdata?block_data=parameter1

**Comment by zachhildreth** [comment]
Closing this, we dont need to add API data if its already on the explorer.
The explorer is more layer 1 blockchain data, while delegates API and shared delegates API is more about DPOPS layer info
